http:
  port: 8082
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  catalog:
    host: localhost
    paths: '/catalog'
  users:
    host: 'localhost'
    paths: ''
  orders:
    host: 'localhost'
    paths: '/graphiql'

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  httpCatalog:
    url: 'http://192.168.1.117:5000/'
  httpUsers:
    url: 'http://localhost:8081/' #cambiar ip
  httpOrders:
    url: 'http://localhost:8080/' #cambiar ip
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
  orders:
    apiEndpoints:
      - orders
    policies:
      - proxy:
        - action:
          serviceEndpoint: httpOrders
          changeOrigin: true
  users:
    apiEndpoints:
      - users
    policies:
      - proxy:
        - action:
          serviceEndpoint: httpUsers
          changeOrigin: true
  products:
    apiEndpoints:
      - catalog
    policies:
      - jwt:
        - action:
            secret: "soa2019"
      - proxy:
        - action:
            serviceEndpoint: httpCatalog
            changeOrigin: true
  ip:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      #- key-auth:
      - jwt:
        - action:
            secret: "soa2019"
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true